Repository openshift/managed-cluster-validating-webhooks, pull requests merged in 2019-12, with the labels that each got.

#11 SREP-2105 - Add image tag to skopeo command
  build/build_deploy.sh
Labels: size/XS

#12 Add OWNERS
  OWNERS
Labels: lgtm, size/S

#14 Add myself as an approver
  OWNERS
Labels: lgtm, size/XS

#13 Remove obsolete single webhook reference
  README.md
Labels: lgtm, size/XS

#9 SREP-2442: Allow kube:admin to create any group
  README.md
  src/webhook/group_validation.py
  templates/20-validation-webhook.deployment.yaml.tmpl
Labels: lgtm, size/S

#18 OSD-2573 Disable group WH in stage during
  templates/10-group-validation.ValidatingWebhookConfiguration.yaml.tmpl
Labels: size/M

#19 OSD-2573 - Clean up selectorsyncset.yaml file, removing group VWC
  build/selectorsyncset.yaml
Labels: size/S
