Repository openshift/managed-cluster-validating-webhooks, pull requests merged in 2020-02, with the labels that each got.

#25 OSD-2744 Added webhook validation for updating namespaces
  Makefile
  src/webhook/__init__.py
  src/webhook/namespace_validation.py
  templates/10-namespace-validation.ValidatingWebhookConfiguration.yaml.tmpl
Labels: lgtm, size/M

#26 Fix build/selectorsyncset.yaml
  build/selectorsyncset.yaml
Labels: size/L

#27 Base image off of ubi
  build/Dockerfile
Labels: lgtm, size/S

#28 Change initcontainer cmd to python3
  build/selectorsyncset.yaml
  templates/20-validation-webhook.deployment.yaml.tmpl
Labels: approved, lgtm, size/XS

#29 Fix bug causing exceptions when trying to delete groups OSD-2923
  src/webhook/group_validation.py
Labels: approved, lgtm, size/XS
