Repository openshift/managed-cluster-validating-webhooks, pull requests merged in 2020-08, with the labels that each got.

#95 Fix bug with group deletion and update group tests
  pkg/webhooks/group/group.go
  pkg/webhooks/group/group_test.go
Labels: approved, lgtm

#96 Update apiGroups denied to regular users
  build/selectorsyncset.yaml
Labels: approved, lgtm

#97 Correct copy/paste error from initial Go port
  pkg/webhooks/group/group.go
Labels: approved, documentation, kind/documentation, lgtm

#99 OSD-4749: Move #96 changes to code
  build/selectorsyncset.yaml
  pkg/webhooks/regularuser/regularuser.go
Labels: approved, lgtm

#98 Always build the syncset
  Makefile
Labels: approved, lgtm

#100 OSD-4884: admin group members can delete users with IDP mismatch
  pkg/webhooks/user/user.go
  pkg/webhooks/user/user_test.go
Labels: approved, kind/bug, lgtm
