Repository openshift/managed-cluster-validating-webhooks, pull requests merged in 2020-05, with the labels that each got.

#65 :bug: When pwd involves a symlink, test, build-sss, lint fail
  Makefile
Labels: approved, kind/bug, lgtm

#63 Add unit tests for group validation webhook OSD-3361
  README.md
  build/selectorsyncset.yaml
  src/webhook/group_validation.py
  src/webhook/namespace_validation.py
  src/webhook/request_helper/validate.py
  src/webhook/test_group_validation.py
  src/webhook/test_namespace_validation.py
  templates/20-validation-webhook.deployment.yaml.tmpl
Labels: approved, lgtm

#68 Fix 2 linting errors: W291 trailing whitespace
  src/webhook/test_group_validation.py
Labels: approved, lgtm

#69 Remove blank line that's causing build failures
  src/webhook/test_namespace_validation.py
Labels: approved, lgtm

#70 This fix the request validation issue
  src/webhook/request_helper/validate.py
Labels: lgtm

#72 Merge OSD-3511 changes
  Makefile
  src/gunicorn.py
  src/webhook/group_validation.py
  src/webhook/namespace_validation.py
  src/webhook/request_helper/responses.py
  src/webhook/subscription_validation.py
  src/webhook/test_group_validation.py
  src/webhook/user_validation.py
Labels: approved, lgtm

#71 Add APAC approver
  OWNERS
Labels: approved, lgtm

#75 Add unit tests for subscription_validation.py OSD-3364
  src/webhook/subscription_validation.py
  src/webhook/test_subscription_validation.py
Labels: approved, lgtm

#76 OSD-3683: Remove subscription webhook
  Makefile
  build/selectorsyncset.yaml
  src/webhook/__init__.py
  src/webhook/subscription_validation.py
  src/webhook/test_subscription_validation.py
  templates/10-subscription-validation.ValidatingWebhookConfiguration.yaml.tmpl
Labels: approved, lgtm
