Repository openshift/managed-cluster-validating-webhooks, pull requests merged in 2025-08, with the labels that each got.

#387 SREP-1565 - Remove cluster-admins exception from namespaces webhook
  pkg/webhooks/namespace/namespace.go
  pkg/webhooks/namespace/namespace_test.go
Labels: approved, lgtm

#386 SREP-769 - Only allow 'openshift.io/cluster-monitoring: true' label to be removed from namespaces
  pkg/webhooks/namespace/namespace.go
  pkg/webhooks/namespace/namespace_test.go
Labels: approved, lgtm

#385 Konflux managed cluster validating webhooks
  .tekton/managed-cluster-validating-webhooks-pull-request.yaml
  .tekton/managed-cluster-validating-webhooks-push.yaml
  build/Dockerfile
Labels: approved, lgtm

#390 [SREP-1045] Disabled e-2-e test due to missing MustGather CRD
  test/e2e/validation_webhook_tests.go
Labels: approved, lgtm

#393 Revert "SREP-1565 - Remove cluster-admins exception from namespaces webhook"
  pkg/webhooks/namespace/namespace.go
  pkg/webhooks/namespace/namespace_test.go
Labels: approved, lgtm

#394 Update boilerplate
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
  boilerplate/openshift/golang-osd-e2e/update
  test/e2e/Dockerfile
  test/e2e/e2e-template.yml
Labels: approved, lgtm

#391 OSD-30954 Update Renovate and on-cel expression changes
  .github/renovate.json
  .tekton/managed-cluster-validating-webhooks-pull-request.yaml
  .tekton/managed-cluster-validating-webhooks-push.yaml
Labels: approved, tide/merge-method-squash, lgtm

#398 OSD-31048:Update Make file and e2e Dockerfile
  Makefile
  boilerplate/_data/last-boilerplate-commit
  test/e2e/Dockerfile
Labels: approved, lgtm, jira/valid-reference
